name: Prettier Code Formatting Check

on:
  pull_request: # Run on pull requests
  push:         # Run on pushes to branches
    branches:
      - main       # Specify branches to check formatting on

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Match your project's Node.js version

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Check Code Formatting
        run: npx prettier --check "**/*.{js,ts,jsx,tsx,css,scss,html,json,yaml,md}"
